version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  lint:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Black formatter check
          command: |
            . venv/bin/activate
            black --check app tests
      - run:
          name: Run Flake8 linter
          command: |
            . venv/bin/activate
            flake8 app tests --max-line-length=100 --exclude=venv,__pycache__

  deploy-heroku:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
            git push -f heroku main
      - run:
          name: Run migrations on Heroku
          command: heroku run "alembic upgrade head" -a $HEROKU_APP_NAME

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - lint
      - deploy-heroku:
          requires:
            - lint
          filters:
            branches:
              only: main
